global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 1.0 #2.0
   publish_frequency: 0.5 #2.0
   width: 5 #20.0 
   height: 5 #20.0
   resolution: 0.02 #0.05
   static_map: true
   rolling_window: false
   transform_tolerance: 0.5 #added
